apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacoffeeshop-deployment
  labels:
    app.kubernetes.io/name: javacoffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: javacoffeeshop
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: keptndemoapp
        app.kubernetes.io/name: javacoffeeshop
        app.kubernetes.io/version: 0.8.0
        keptn.sh/pre-deployment-tasks: pre-deploy-task
        keptn.sh/post-deployment-tasks: post-deploy-task
        # keptn.sh/pre-deployment-evaluations: 
        keptn.sh/post-deployment-evaluations: post-deploy-eval
    spec:
      containers:
      - name: javacoffeeshop
        image: shmdus/java-app:24
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 160m
            memory: 200Mi
