apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnEvaluationDefinition
metadata:
  name: post-deploy-eval
  namespace: keptndemo
spec:
  objectives:
    - keptnMetricRef:
        name: cpu-throttling
        namespace: keptndemo
      evaluationTarget: "<15"
